/*
 * Project iMobile
 * An API to work with Money
 *
 * OpenAPI spec version: 1.0.1
 * Contact: dulitha@cabbageapps.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.interblocks.imobile.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.interblocks.imobile.api.model.SecurityImage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ModelConfiguration
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-03-04T05:01:25.177Z")
public class ModelConfiguration   {
  @JsonProperty("security_images")
  private List<SecurityImage> securityImages = new ArrayList<SecurityImage>();

  @JsonProperty("auth_types")
  private List<SecurityImage> authTypes = new ArrayList<SecurityImage>();

  public ModelConfiguration securityImages(List<SecurityImage> securityImages) {
    this.securityImages = securityImages;
    return this;
  }

  public ModelConfiguration addSecurityImagesItem(SecurityImage securityImagesItem) {
    this.securityImages.add(securityImagesItem);
    return this;
  }

   /**
   * list of security images
   * @return securityImages
  **/
  @ApiModelProperty(required = true, value = "list of security images")
  public List<SecurityImage> getSecurityImages() {
    return securityImages;
  }

  public void setSecurityImages(List<SecurityImage> securityImages) {
    this.securityImages = securityImages;
  }

  public ModelConfiguration authTypes(List<SecurityImage> authTypes) {
    this.authTypes = authTypes;
    return this;
  }

  public ModelConfiguration addAuthTypesItem(SecurityImage authTypesItem) {
    this.authTypes.add(authTypesItem);
    return this;
  }

   /**
   * list of auth types
   * @return authTypes
  **/
  @ApiModelProperty(value = "list of auth types")
  public List<SecurityImage> getAuthTypes() {
    return authTypes;
  }

  public void setAuthTypes(List<SecurityImage> authTypes) {
    this.authTypes = authTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelConfiguration _configuration = (ModelConfiguration) o;
    return Objects.equals(this.securityImages, _configuration.securityImages) &&
        Objects.equals(this.authTypes, _configuration.authTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(securityImages, authTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelConfiguration {\n");
    
    sb.append("    securityImages: ").append(toIndentedString(securityImages)).append("\n");
    sb.append("    authTypes: ").append(toIndentedString(authTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

