/*
 * Project iMobile
 * An API to work with Money
 *
 * OpenAPI spec version: 1.0.1
 * Contact: dulitha@cabbageapps.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.interblocks.imobile.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Locations
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-03-04T04:51:09.939Z")
public class Locations   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("bankName")
  private String bankName = null;

  @JsonProperty("branchName")
  private String branchName = null;

  @JsonProperty("branchLocation")
  private String branchLocation = null;

  @JsonProperty("atmName")
  private String atmName = null;

  @JsonProperty("atmLocation")
  private String atmLocation = null;

  public Locations id(String id) {
    this.id = id;
    return this;
  }

   /**
   * unqiue identification for transactions
   * @return id
  **/
  @ApiModelProperty(required = true, value = "unqiue identification for transactions")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Locations bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * name of the branch's bank
   * @return bankName
  **/
  @ApiModelProperty(required = true, value = "name of the branch's bank")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public Locations branchName(String branchName) {
    this.branchName = branchName;
    return this;
  }

   /**
   * name of the perticuler branch
   * @return branchName
  **/
  @ApiModelProperty(required = true, value = "name of the perticuler branch")
  public String getBranchName() {
    return branchName;
  }

  public void setBranchName(String branchName) {
    this.branchName = branchName;
  }

  public Locations branchLocation(String branchLocation) {
    this.branchLocation = branchLocation;
    return this;
  }

   /**
   * location of the branch
   * @return branchLocation
  **/
  @ApiModelProperty(required = true, value = "location of the branch")
  public String getBranchLocation() {
    return branchLocation;
  }

  public void setBranchLocation(String branchLocation) {
    this.branchLocation = branchLocation;
  }

  public Locations atmName(String atmName) {
    this.atmName = atmName;
    return this;
  }

   /**
   * name of the atm
   * @return atmName
  **/
  @ApiModelProperty(required = true, value = "name of the atm")
  public String getAtmName() {
    return atmName;
  }

  public void setAtmName(String atmName) {
    this.atmName = atmName;
  }

  public Locations atmLocation(String atmLocation) {
    this.atmLocation = atmLocation;
    return this;
  }

   /**
   * location of the atm
   * @return atmLocation
  **/
  @ApiModelProperty(required = true, value = "location of the atm")
  public String getAtmLocation() {
    return atmLocation;
  }

  public void setAtmLocation(String atmLocation) {
    this.atmLocation = atmLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Locations locations = (Locations) o;
    return Objects.equals(this.id, locations.id) &&
        Objects.equals(this.bankName, locations.bankName) &&
        Objects.equals(this.branchName, locations.branchName) &&
        Objects.equals(this.branchLocation, locations.branchLocation) &&
        Objects.equals(this.atmName, locations.atmName) &&
        Objects.equals(this.atmLocation, locations.atmLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bankName, branchName, branchLocation, atmName, atmLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Locations {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    branchName: ").append(toIndentedString(branchName)).append("\n");
    sb.append("    branchLocation: ").append(toIndentedString(branchLocation)).append("\n");
    sb.append("    atmName: ").append(toIndentedString(atmName)).append("\n");
    sb.append("    atmLocation: ").append(toIndentedString(atmLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

