/**
 * Project iMobile
 * An API to work with Money
 *
 * OpenAPI spec version: 1.0.1
 * Contact: dulitha@cabbageapps.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface Notification {
    /**
     * unqiue identification for notification
     */
    id?: string;

    /**
     * type of notification
     */
    type?: Notification.TypeEnum;

    user?: models.User;

    /**
     * read/ unread status
     */
    status?: Notification.StatusEnum;

}
export namespace Notification {
    export enum TypeEnum {
        FundsReceived = <any> 'FundsReceived',
        MoneySent = <any> 'MoneySent',
        PaymentMade = <any> 'PaymentMade',
        NewFeatures = <any> 'NewFeatures'
    }
    export enum StatusEnum {
        Read = <any> 'Read',
        UnRead = <any> 'UnRead'
    }
}
